author: D4RKK
name: aCore
version: 3.0.0
api-version: 1.14
depend: [ProtocolLib, PlaceholderAPI]
commands:
  replay:
    description: Main Replay command
    aliases: [rp]
main: me.joaomanoel.d4rkk.dev.Core
