#Languages available: PT_BR(Portuguese), ES_ES(Spanish), EN_US(English), KO_KR(Korean), ZH_CH(Chinese), JA_JP (Japanese)
defaultLanguage: 'EN_US'
leaderboard:
 show-role: true

database:
 # Currently available database types: MongoDB, MySQL
 type: 'MySQL'
 mysql:
  # Use Hikari
  hikari: false
  # Use MariaDB driver
  mariadb: false
  # Host to access MySQL
  host: 'localhost'
  # Port to access MySQL
  port: '3306'
  # Database name in MySQL
  name: 'server'
  # MySQL access user
  user: 'root'
  # MySQL access password
  pass: ''
 mongodb:
   # MongoDB access URL
   # https://docs.mongodb.com/manual/reference/connection-string/
   url: ''

messages:
 invite: "&a%leader% &7convidou você para a Party dele!\n&rVocê pode "
 accept: "&aClique para aceitar o convite de Party de %leader%&r"
 reject: "&cClique para negar o convite de Party de %leader%&r"
 join: "&a%member% entrou na Party!&r"
 leave: "&c%member% saiu da Party!&r"
 transfer: "&a%member% se tornou o novo Líder da Party!&r"
 kick: "&c%leader% te expulsou da Party!&r"
 invite_buttons:
  accept: "&a&lACEITAR&7"
  reject: "&c&lNEGAR&7"
 hover_accept: "&7Clique para aceitar o convite de Party de %leader%&r"
 hover_reject: "&7Clique para negar o convite de Party de %leader%&r"
 or: " &7ou&r "  # Nova chave para "ou"

